### ISSUE TITLE
Attempting to run causes an exception

### ISSUE THREAD

**Issue by jharrison** [wang-boyu/agents-and-networks-in-python#1]
I can run `test_environment.py` successfully:
```bash
% python3 test_environment.py
>>> Development environment passes all tests!
```

But then this happens:
```bash
% python3 src/visualization/run.py
2022-02-08 14:45:47,177 - server - INFO - <module> - Entered module: server
Traceback (most recent call last):
  File "src/visualization/run.py", line 3, in <module>
    from server import server
  File "/Users/jharrison/code/mesa/gmu-social-in-python/src/visualization/server.py", line 84, in <module>
    server = ModularServer(
  File "/Users/jharrison/code/mesa/mesa-geo/examples/GeoSIR/src/mesa-geo/mesa_geo/visualization/ModularVisualization.py", line 276, in __init__
    self.reset_model()
  File "/Users/jharrison/code/mesa/mesa-geo/examples/GeoSIR/src/mesa-geo/mesa_geo/visualization/ModularVisualization.py", line 302, in reset_model
    self.model = self.model_cls(**model_params)
  File "/Users/jharrison/code/mesa/gmu-social-in-python/src/model/gmu_social.py", line 78, in __init__
    self.__load_buildings_from_file(gmu_buildings_file, crs=crs)
  File "/Users/jharrison/code/mesa/gmu-social-in-python/src/model/gmu_social.py", line 121, in __load_buildings_from_file
    buildings_df["centroid"] = [(x, y) for x, y in zip(buildings_df.centroid.x, buildings_df.centroid.y)]
  File "/usr/local/anaconda3/lib/python3.8/site-packages/geopandas/geoseries.py", line 262, in x
    return _delegate_property("x", self)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/geopandas/base.py", line 66, in _delegate_property
    data = getattr(a_this, op)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/geopandas/array.py", line 882, in x
    return vectorized.get_x(self.data)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/geopandas/_vectorized.py", line 910, in get_x
    return _unary_op("x", data, null_value=np.nan)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/geopandas/_vectorized.py", line 461, in _unary_op
    data = [getattr(geom, op, null_value) for geom in left]
  File "/usr/local/anaconda3/lib/python3.8/site-packages/geopandas/_vectorized.py", line 461, in <listcomp>
    data = [getattr(geom, op, null_value) for geom in left]
  File "/usr/local/anaconda3/lib/python3.8/site-packages/shapely/geometry/point.py", line 66, in x
    return self.coords[0][0]
  File "/usr/local/anaconda3/lib/python3.8/site-packages/shapely/coords.py", line 85, in __getitem__
    raise IndexError("index out of range")
IndexError: index out of range
```

Do you have any suggestions?

**Comment by wang-boyu** [comment]
Wow, thank you! I made this repo mainly for myself and didn't expect anyone to actually run it.

From your backtrace, it appears that the environments are a bit intertwined? The program executed from `gmu-social-in-python/src/visualization/server.py` but somehow calls `src/mesa-geo/mesa_geo/visualization/ModularVisualization.py` from your `mesa/mesa-geo/examples/GeoSIR`, while using some libraries from Anaconda.

Can we try to use a separate virtual environment just for this repo with `venv`, and install dependencies from the `requirements.txt` file? You probably would need Python 3.8 and above.

If the issue still persists, you may provide me your Python version and I'll try to reproduce.

**Comment by jharrison** [comment]
Glad to help test out your code. Thanks for making it public! :)

Your suggestion worked (though I had to install xcode command line tools first since I just upgraded my os a few days ago). However, now when I run it, the map comes up but it doesn't seem to do anything when I click Start:
![image](https://user-images.githubusercontent.com/251553/153081469-c2c3e5aa-1a1f-4fe0-aca0-b5d7788799fc.png)

Any ideas?

**Comment by wang-boyu** [comment]
That's just the base map from `Leaflet.js` in `mesa-geo`, and the shape files of GMU campus don't seem to get loaded or rendered correctly. Before running the model it should look like this:

<img width="1200" alt="Screenshot 2022-02-08 at 5 23 39 PM" src="https://user-images.githubusercontent.com/10785873/153086060-894e7885-504c-4429-8728-2d24801497d5.png">

How about clearing the browser cache and doing a hard refresh of the webpage? Not sure whether this will help though.

If not may I have your Python version number? I can produce a dependency lock file to make sure that we're using the same packages.

Thanks for the help!

**Comment by jharrison** [comment]
The hard refresh worked!
![image](https://user-images.githubusercontent.com/251553/153215585-e3f72123-bedb-481c-9476-7f16812d9172.png)

**Comment by wang-boyu** [comment]
Excellent! Have fun : )
